/// Model representing an AI-generated drill animation
/// Generated by Gemini and rendered by DrillAnimationPainter
class DrillAnimationData {
  final List<AnimatedPlayer> players;
  final List<AnimatedBall> balls;
  final List<Equipment> equipment;
  final int durationMs;
  final String description;

  DrillAnimationData({
    required this.players,
    required this.balls,
    required this.equipment,
    required this.durationMs,
    required this.description,
  });

  factory DrillAnimationData.fromJson(Map<String, dynamic> json) {
    return DrillAnimationData(
      players: (json['players'] as List?)
              ?.map((p) => AnimatedPlayer.fromJson(p))
              .toList() ??
          [],
      balls: (json['balls'] as List?)
              ?.map((b) => AnimatedBall.fromJson(b))
              .toList() ??
          [],
      equipment: (json['equipment'] as List?)
              ?.map((e) => Equipment.fromJson(e))
              .toList() ??
          [],
      durationMs: json['duration_ms'] ?? 5000,
      description: json['description'] ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'players': players.map((p) => p.toJson()).toList(),
      'balls': balls.map((b) => b.toJson()).toList(),
      'equipment': equipment.map((e) => e.toJson()).toList(),
      'duration_ms': durationMs,
      'description': description,
    };
  }
}

/// Represents a player with movement path
class AnimatedPlayer {
  final String id;
  final List<Position> path; // Movement waypoints
  final String color; // hex color string
  final String label; // "P1", "P2", etc.

  AnimatedPlayer({
    required this.id,
    required this.path,
    required this.color,
    required this.label,
  });

  factory AnimatedPlayer.fromJson(Map<String, dynamic> json) {
    return AnimatedPlayer(
      id: json['id'] ?? '',
      path: (json['path'] as List?)
              ?.map((p) => Position.fromJson(p))
              .toList() ??
          [],
      color: json['color'] ?? '#FF0000',
      label: json['label'] ?? 'P',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'path': path.map((p) => p.toJson()).toList(),
      'color': color,
      'label': label,
    };
  }
}

/// Represents a ball with movement
class AnimatedBall {
  final String id;
  final List<Position> path;
  final bool isDribbled; // true = follows player, false = passed/kicked

  AnimatedBall({
    required this.id,
    required this.path,
    this.isDribbled = false,
  });

  factory AnimatedBall.fromJson(Map<String, dynamic> json) {
    return AnimatedBall(
      id: json['id'] ?? '',
      path: (json['path'] as List?)
              ?.map((p) => Position.fromJson(p))
              .toList() ??
          [],
      isDribbled: json['is_dribbled'] ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'path': path.map((p) => p.toJson()).toList(),
      'is_dribbled': isDribbled,
    };
  }
}

/// Represents static equipment (cones, goals, etc.)
class Equipment {
  final String type; // "cone", "goal", "bib_pile", etc.
  final Position position;
  final String color;

  Equipment({
    required this.type,
    required this.position,
    required this.color,
  });

  factory Equipment.fromJson(Map<String, dynamic> json) {
    return Equipment(
      type: json['type'] ?? 'cone',
      position: Position.fromJson(json['position'] ?? {}),
      color: json['color'] ?? '#FFA500',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'type': type,
      'position': position.toJson(),
      'color': color,
    };
  }
}

/// 2D position with normalized coordinates (0.0 - 1.0)
/// 0.0 = left/top, 1.0 = right/bottom
class Position {
  final double x;
  final double y;
  final int? timeMs; // Optional: when to reach this position in animation

  Position({
    required this.x,
    required this.y,
    this.timeMs,
  });

  factory Position.fromJson(Map<String, dynamic> json) {
    return Position(
      x: (json['x'] ?? 0.0).toDouble(),
      y: (json['y'] ?? 0.0).toDouble(),
      timeMs: json['time_ms'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'x': x,
      'y': y,
      if (timeMs != null) 'time_ms': timeMs,
    };
  }
}
