import '../models/badge_model.dart';

// Static data for Little Kickers badge system
List<Badge> allBadges = [
  // Little Kicks (Red - 0xFFE31C23)
  Badge(
    id: 'lk_attention_listening',
    title: 'Attention & Listening',
    ageGroup: 'Little Kicks',
    iconAsset: 'star',
    colorHex: '0xFFE31C23',
    description: 'Learning to follow the coach for instructions',
  ),
  Badge(
    id: 'lk_sharing',
    title: 'Sharing',
    ageGroup: 'Little Kicks',
    iconAsset: 'heart',
    colorHex: '0xFFE31C23',
    description: 'Learning to share equipment and take turns',
  ),
  Badge(
    id: 'lk_kicking',
    title: 'Kicking',
    ageGroup: 'Little Kicks',
    iconAsset: 'foot_ball',
    colorHex: '0xFFE31C23',
    description: 'Developing basic kicking skills',
  ),
  Badge(
    id: 'lk_confidence',
    title: 'Confidence',
    ageGroup: 'Little Kicks',
    iconAsset: 'smiley',
    colorHex: '0xFFE31C23',
    description: 'Building confidence in football skills',
  ),
  
  // Junior Kickers (Yellow - 0xFFFFD700)
  Badge(
    id: 'jk_kicking',
    title: 'Kicking',
    ageGroup: 'Junior Kickers',
    iconAsset: 'foot_ball',
    colorHex: '0xFFFFD700',
    description: 'Improving kicking accuracy and power',
  ),
  Badge(
    id: 'jk_imagination',
    title: 'Imagination',
    ageGroup: 'Junior Kickers',
    iconAsset: 'lightbulb',
    colorHex: '0xFFFFD700',
    description: 'Using imagination in games and activities',
  ),
  Badge(
    id: 'jk_physical_literacy',
    title: 'Physical Literacy',
    ageGroup: 'Junior Kickers',
    iconAsset: 'jumping_person',
    colorHex: '0xFFFFD700',
    description: 'Developing fundamental movement skills',
  ),
  Badge(
    id: 'jk_team_player',
    title: 'Team Player',
    ageGroup: 'Junior Kickers',
    iconAsset: 'two_figures',
    colorHex: '0xFFFFD700',
    description: 'Working well with teammates',
  ),
  
  // Mighty Kickers (Green - 0xFF4CAF50)
  Badge(
    id: 'mk_leadership',
    title: 'Leadership',
    ageGroup: 'Mighty Kickers',
    iconAsset: 'leadership',
    colorHex: '0xFF4CAF50',
    description: 'Taking on leadership roles in activities',
  ),
  Badge(
    id: 'mk_physical_literacy',
    title: 'Physical Literacy',
    ageGroup: 'Mighty Kickers',
    iconAsset: 'jumping_person',
    colorHex: '0xFF4CAF50',
    description: 'Advanced fundamental movement skills',
  ),
  Badge(
    id: 'mk_all_rounder',
    title: 'All-rounder',
    ageGroup: 'Mighty Kickers',
    iconAsset: 'all_rounder',
    colorHex: '0xFF4CAF50',
    description: 'Demonstrating all-around skills',
  ),
  Badge(
    id: 'mk_problem_solver',
    title: 'Problem Solver',
    ageGroup: 'Mighty Kickers',
    iconAsset: 'puzzle',
    colorHex: '0xFF4CAF50',
    description: 'Solving problems during games',
  ),
  Badge(
    id: 'mk_kicking',
    title: 'Kicking',
    ageGroup: 'Mighty Kickers',
    iconAsset: 'foot_ball',
    colorHex: '0xFF4CAF50',
    description: 'Advanced kicking techniques',
  ),
  Badge(
    id: 'mk_match_play',
    title: 'Match Play',
    ageGroup: 'Mighty Kickers',
    iconAsset: 'match_play',
    colorHex: '0xFF4CAF50',
    description: 'Participating in match play situations',
  ),
  
  // Mega Kickers (Purple - 0xFF9C27B0)
  Badge(
    id: 'mega_attacking',
    title: 'Attacking',
    ageGroup: 'Mega Kickers',
    iconAsset: 'attacking',
    colorHex: '0xFF9C27B0',
    description: 'Developing attacking strategies',
  ),
  Badge(
    id: 'mega_defending',
    title: 'Defending',
    ageGroup: 'Mega Kickers',
    iconAsset: 'defending',
    colorHex: '0xFF9C27B0',
    description: 'Learning defensive techniques',
  ),
  Badge(
    id: 'mega_tactician',
    title: 'Tactician',
    ageGroup: 'Mega Kickers',
    iconAsset: 'tactician',
    colorHex: '0xFF9C27B0',
    description: 'Understanding tactical concepts',
  ),
  Badge(
    id: 'mega_captain',
    title: 'Captain',
    ageGroup: 'Mega Kickers',
    iconAsset: 'captain',
    colorHex: '0xFF9C27B0',
    description: 'Leading the team as captain',
  ),
  Badge(
    id: 'mega_all_rounder',
    title: 'All-rounder',
    ageGroup: 'Mega Kickers',
    iconAsset: 'all_rounder',
    colorHex: '0xFF9C27B0',
    description: 'Master of all skills',
  ),
  Badge(
    id: 'mega_referee',
    title: 'Referee',
    ageGroup: 'Mega Kickers',
    iconAsset: 'referee',
    colorHex: '0xFF9C27B0',
    description: 'Understanding rules and fair play',
  ),
];